# .github/workflows/cleanup.yml
name: Supabase Storage Maintenance

on:
  schedule:
    - cron: '0 0 * * *' 
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  # JOB 1: Deploy (CORRETTO)
  deploy_function:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
      - name: Deploy Cleanup Storage Function
        uses: supabase/setup-cli@v1
        with:
          version: latest
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          npx supabase functions deploy cleanup-storage --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}
          echo "Deploy Edge Function completato."
          
  # JOB 2: Esecuzione (CON INDENTAZIONE CORRETTA)
  run_cleanup_cron:
    needs: deploy_function
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Call Cleanup Edge Function # 6 spazi
        env:                             # 8 spazi
          FUNCTION_URL: https://${{ secrets.SUPABASE_PROJECT_ID }}.supabase.co/functions/v1/cleanup-storage # 10 spazi
          ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }} # 10 spazi
        run: |                           # 8 spazi
          echo "Avvio della funzione di pulizia tramite cron..."
          curl -X POST "$FUNCTION_URL" \
          -H "Authorization: Bearer $ANON_KEY" \
          -H "Content-Type: application/json" \
          -d "{}"
          echo "Richiesta Edge Function inviata per la pulizia dei file scaduti."
